
apiVersion: isc.ibm.com/v1
kind: CP4SThreatManagement
metadata:
     name: threatmgmt
     namespace: cp4s
spec:
     acceptLicense: true
     basicDeploymentConfiguration:
         adminUser: cloudpak-admin
         domain: ""
         storageClass: ""
     extendedDeploymentConfiguration:
         airgapInstall: false
         backupStorageClass: ""
         backupStorageSize: ""
         imagePullPolicy: IfNotPresent
         repository: cp.icr.io/cp/cp4s
         repositoryType: entitled
         roksAuthentication: false
     threatManagementCapabilities:
         deployDRC: true
         deployRiskManager: true
         deployThreatInvestigator: true