apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: db2ucluster
  namespace: db2OnOcpProjectName
spec:
  size: 1
  license:
    db2_license
  account:
    imagePullSecrets:
      - ibm-db2-registry
    privileged: true
  environment:
    dbType: db2oltp
    instance:
      password: db2AdminUserPassword
  version: db2InstanceVersion
  podConfig:
    db2u:
      resource:
        db2u:
          requests:
            cpu: db2Cpu
            memory: db2Memory
          limits:
            cpu: db2Cpu
            memory: db2Memory
  storage:
    - name: share
      type: create
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: db2StorageSize
        storageClassName: db2OnOcpStorageClassName
