---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: ibmc-file-custom-gold-gid
parameters:
  billingType: hourly
  classVersion: "2"
  gidAllocate: "true"
  sizeIOPSRange: |-
    [20-39]Gi:[1000-1000]
    [40-79]Gi:[2000-2000]
    [80-99]Gi:[4000-4000]
    [100-499]Gi:[6000-6000]
    [500-999]Gi:[10000-10000]
    [1000-1999]Gi:[20000-20000]
    [2000-2999]Gi:[40000-40000]
    [3000-3999]Gi:[48000-48000]
    [4000-7999]Gi:[48000-48000]
    [8000-9999]Gi:[48000-48000]
    [10000-12000]Gi:[48000-48000]
  type: Performance
provisioner: ibm.io/ibmc-file
reclaimPolicy: Delete
volumeBindingMode: Immediate
