apiVersion: orchestrator.aiops.ibm.com/v1alpha1
kind: Installation
metadata:
  name: ibm-cp-watson-aiops
spec:
  automationFoundation: {}
  imagePullSecret: ibm-entitlement-key
  license:
    accept: true
  pakModules:
    - enabled: true
      name: aiManager
    - enabled: true
      name: aiopsFoundation
    - enabled: true
      name: applicationManager
  size: small
  storageClass: portworx-fs
  storageClassLargeBlock: portworx-aiops