apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-bigsql-operator-catalog-subscription
  namespace: OPERATOR_NAMESPACE
spec:   
  channel: v7.2
  installPlanApproval: Automatic
  name: ibm-bigsql-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace