apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/instance: ibm-cpd-ws-runtimes-operator-catalog-subscription
    app.kubernetes.io/managed-by: ibm-cpd-ws-runtimes-operator
    app.kubernetes.io/name: ibm-cpd-ws-runtimes-operator
  name: ibm-cpd-ws-runtimes-operator
  namespace: OPERATOR_NAMESPACE  # Pick the project that contains the Cloud Pak for Data operator
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-cpd-ws-runtimes
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-cpd-ws-runtimes.v1.0.1