###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: operands-playbook-config
  namespace: cs-operands-installer
data:
  config.yaml: |
    # Common Service namespace, currently does not support updating it
    namespace: ibm-common-services

    # Image repository, only update when using custom registry
    image_repo: quay.io/opencloudio
