###############################################################################
##
##Licensed Materials - Property of IBM
##
##(C) Copyright IBM Corp. 2021. All Rights Reserved.
##
##US Government Users Restricted Rights - Use, duplication or
##disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
##
###############################################################################
apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4badeploy
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.1
spec:
  appVersion: 21.0.1.1

  ## MUST exist, used to accept ibm license, valid value only can be "accept" 
  ibm_license: ""

  #################################################################################################################
  ##  The contents of this template CR file reflect only the specific parameters and configuration
  ##  settings applicable to the represented ICP4A capability.
  ##
  ##  These values/configuration sections are to be used when manually assembling or updating the main
  ##  ICP4A CR that is being applied in order to install and ICP4A environment.
  ##
  ##  If you are in the process of preparing a new install of an ICP4A environment, you should merge
  ##  the required values and configuration sections from this file into the
  ##  starting point CR template: ibm_cp4a_cr_enterprise[_FC]_foundation.yaml available in the
  ##  same location as this template.
  ##
  ##  If you updating an existing ICP4A environment, you should merge the required values and configuration
  ##  sections from this templated in the main ICP4A CR file already applied in the environment.
  ##
  ######################################################################################################################


  ##########################################################################
  ## This section contains the shared configuration for all CP4A components #
  ##########################################################################
  shared_configuration:

    ## CP4A patterns or capabilities to be deployed. This CR represents the "decisions_ads" pattern that brings ADS Designer and ADS Runtime.
    sc_deployment_patterns: decisions_ads

    ## The optional components to be installed if listed here.
    ## This is normally populated by the User script based on input from the user.
    ## User can also manually specify the optional components to be deployed here.
    ## ADS has two 'ads_designer' and 'ads_runtime' optional components. If 'ads_runtime' is here, it is possible to also add 'bai'.
    ## If ads_designer is set, you also have to set the 'ads_configuration.decision_designer.enabled' flag to true to install it.
    ## If ads_runtime is set, you also have to set the 'ads_configuration.decision_runtime.enabled' flag to true to install it.
    sc_optional_components:


  ########################################################################
  ########   IBM Business Automation Decision Services            ########
  ########################################################################

  ads_configuration:

    decision_designer:
      enabled: false
      admin_secret_name: ibm-dba-ads-designer-secret

      # Config maps containing certificates to trust
      git_servers_certs:
      ml_providers_certs:
      other_trusted_certs:

#      # Optional: you can add custom annotations to routes or ingresses.
#
#      # For routes
#      route_ingress_annotations:
#        - haproxy.router.openshift.io/timeout: 1m
#
#      # For k8s Ingresses on certified kubernetes (CNCF)
#      route_ingress_annotations:
#        nginx.ingress.kubernetes.io/proxy-body-size: 8m

      ingress:
        # Optional: If omitted, calculated as designer-ads-{{ sc_deployment_hostname_suffix }} for ROKS or designer.ads.{{ sc_deployment_hostname_suffix }} otherwise.
        # hostname:
        tls_secret_name: ibm-dba-ads-designer-tls-cert

#        # Optional: you can provide a custom CA for routes.
#        tls_ca_secret_name:

      embedded_build_and_run:
        # Embedded build and run can be disabled
        enabled: true
        # Embedded Runtime configuration
        runtime:
#        # Optional: you can add custom annotations to routes or ingresses.
          route_ingress_annotations:
            # For routes
            - haproxy.router.openshift.io/balance: roundrobin
#            - haproxy.router.openshift.io/timeout: 1m
#          # For k8s Ingresses on certified kubernetes (CNCF)
#            - nginx.ingress.kubernetes.io/proxy-body-size: 8m

          ingress:
            # Optional: If omitted, calculated as embedded-runtime-ads-{{ sc_deployment_hostname_suffix }} for ROKS, embedded-runtime.ads.{{ sc_deployment_hostname_suffix }} otherwise.
            # hostname:
            tls_secret_name: ibm-dba-ads-designer-embedded-runtime-tls-cert
#           # Optional: you can provide a custom CA for routes.
#            tls_ca_secret_name:

        decision_archive_repo:
          persistence:
            use_dynamic_provisioning: true
#           # defaulted to shared_configuration.storage_configuration.sc_dynamic_storage_classname
#           # or shared_configuration.storage_configuration.sc_fast_file_storage_classname if use_dynamic_provisioning is false or shared_configuration.storage_configuration.sc_dynamic_storage_classname is not defined
#            storage_class_name:
            resources:
              requests:
                storage: "50Gi"

    decision_runtime:
      enabled: false
      admin_secret_name: ibm-dba-ads-runtime-secret
      # Authentication mode can be "basic" or "ums".
      authentication_mode: "basic"

      # Only for debugging, default value is true.
      internal_tls: true

      # Optional: you can add custom annotations to routes or ingresses.
      route_ingress_annotations:
#       # For routes
        - haproxy.router.openshift.io/balance: roundrobin
#        - haproxy.router.openshift.io/timeout: 1m
#      # For k8s Ingresses on certified kubernetes (CNCF)
#        - nginx.ingress.kubernetes.io/proxy-body-size: 8m


      ingress:
        # Optional: If omitted, calculated as runtime-ads-{{ sc_deployment_hostname_suffix }} for ROKS or runtime.ads.{{ sc_deployment_hostname_suffix }} otherwise.
        # hostname:
        tls_secret_name: ibm-dba-ads-runtime-tls-cert

#        # Optional: you can provide a custom CA for routes.
#        tls_ca_secret_name:

      # Event emitter, needs BAI.
      event_emitter:
        enabled: true  # default true, optional. Will be ignored if BAI is not installed.
#        kafka_topic:  # default "ads-decision-execution-common-data", optional.
#        kafka_properties_config_map_name: # default null, see KC for content. Optional.
#        elasticsearch_index:  # default "ads-decision-execution-common-data", optional. See KC for elasticsearch indexes names criteria.
#        allow_missing_events : # default true, optional.
#        queue_capacity:  # default 50000, optional.
#        dequeur_threads: # default null,  as startup time, optional.


    rr_integration:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-rrintegration
        tag: 21.0.1-IF001

      resources:
        requests:
          cpu: '200m'
          memory: '256Mi'
        limits:
          cpu: '500m'
          memory: '512Mi'

    mongo:
#      # Optional: defaulted to false. (true in demo mode)
#      # Embedded mongoDB is not recommended in production. It is not enabled by default.
#      use_embedded: false
      # If you provide an external mongo db, fill the mongo connection string in the admin secret.
      admin_secret_name: ibm-dba-ads-mongo-secret
      image:
        repository: cp.icr.io/cp/cp4a/ads/mongo
        tag: 4.2.12

      persistence:
        use_dynamic_provisioning: true
#       # Optional: defaulted to shared_configuration.storage_configuration.sc_dynamic_storage_classname
#       # or shared_configuration.storage_configuration.sc_fast_file_storage_classname if use_dynamic_provisioning is false or shared_configuration.storage_configuration.sc_dynamic_storage_classname is not defined
#        storage_class_name:
        resources:
          requests:
            storage: 3Gi

      resources:
        requests:
          cpu: '500m'
          memory: '256Mi'
        limits:
          cpu: '1000m'
          memory: '1Gi'

    front:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-front
        tag: 21.0.1-IF001

      replica_count: 1
      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    download_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-download
        tag: 21.0.1-IF001

      replica_count: 2
      resources:
        requests:
          cpu: '100m'
          memory: '200Mi'
        limits:
          cpu: '500m'
          memory: '200Mi'

    rest_api:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-restapi
        tag: 21.0.1-IF001
      replica_count: 2

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    credentials_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-credentials
        tag: 21.0.1-IF001
      replica_count: 2

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    git_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-gitservice
        tag: 21.0.1-IF001
      replica_count: 2

      persistence:
        use_dynamic_provisioning: true
#       # Optional: defaulted to shared_configuration.storage_configuration.sc_dynamic_storage_classname
#       # or shared_configuration.storage_configuration.sc_fast_file_storage_classname if use_dynamic_provisioning is false or shared_configuration.storage_configuration.sc_dynamic_storage_classname is not defined
#        storage_class_name:
        resources:
          requests:
            storage: 6Gi

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    parsing_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-parsing
        tag: 21.0.1-IF001
      replica_count: 2

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    run_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-run
        tag: 21.0.1-IF001
      replica_count: 2

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    embedded_build_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-build
        tag: 21.0.1-IF001
      replica_count: 2

      persistence:
        use_dynamic_provisioning: true
#       # defaulted to shared_configuration.storage_configuration.sc_dynamic_storage_classname
#       # or shared_configuration.storage_configuration.sc_fast_file_storage_classname if use_dynamic_provisioning is false or shared_configuration.storage_configuration.sc_dynamic_storage_classname is not defined
#        storage_class_name:
        resources:
          requests:
            storage: '6Gi'

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    embedded_runtime_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-runtime
        tag: 21.0.1-IF001
      replica_count: 2

      # Whether the decision runtime should include an exception stack trace when an incident occurs.
      # This should only be used for debugging purposes, as a stack trace may expose sensitive internal data.
      stack_trace_enabled: false

      tls:
        # whether TLS is required for decision store or ML providers connections (HTTPS protocol)
        enabled: true
        # name of the config map holding the TLS certificates
        certs_config_map_name:
        # whether self-signed certificates are allowed
        allow_self_signed: false
        verify_hostname: true

      cache:
        config:
          expiry: ''
          resources: |-
            <heap unit="entries">100</heap>

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

    decision_runtime_service:
      image:
        repository: cp.icr.io/cp/cp4a/ads/ads-runtime
        tag: 21.0.1-IF001
      replica_count: 2

      # Whether the decision runtime should include an exception stack trace when an incident occurs.
      # This should only be used for debugging purposes, as a stack trace may expose sensitive internal data.
      stack_trace_enabled: false

      tls:
        # whether TLS is required for decision store or ML providers connections (HTTPS protocol)
        enabled: true
        # name of the config map holding the TLS certificates
        certs_config_map_name:
        # whether self-signed certificates are allowed
        allow_self_signed: false
        verify_hostname: true

      cache:
        config:
          expiry: ''
          resources: |-
            <heap unit="entries">100</heap>

      resources:
        requests:
          cpu: '500m'
          memory: '512Mi'
        limits:
          cpu: '2000m'
          memory: '2Gi'

      autoscaling:
        enabled: true
        min_replicas: 2
        max_replicas: 5
        target_cpu_average_utilization: 160

      archive_repository:
        # Left part of the url to access your decision archives.
        # Optional credentials are in decision_runtime.admin_secret_name
        url_prefix: "<Required>"
