apiVersion: apps/v1
kind: Deployment
metadata:
  name: operand-deployment-lifecycle-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operand-deployment-lifecycle-manager
  template:
    metadata:
      labels:
        name: operand-deployment-lifecycle-manager
        app.kubernetes.io/instance: operand-deployment-lifecycle-manager
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: "FREE"
    spec:
      serviceAccountName: operand-deployment-lifecycle-manager
      containers:
        - name: operand-deployment-lifecycle-manager
          # Replace this with the built image name
          image: quay.io/opencloudio/odlm:1.1.0
          command:
          - odlm
          args:
          - "-v=2"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "operand-deployment-lifecycle-manager"