###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ibm-cp4a-operator
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ibm-cp4a-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - icp4a.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/exec
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - '*'
- apiGroups:
  - "extensions"
  resources:
  - "ingresses"
  - "jobs"
  - "deployments"
  - "networkpolicies"
  - "replicasets"
  verbs:
  - "*"
- apiGroups:
  - core.automation.ibm.com
  resources:
  - cartridges
  - automationuiconfigs
  verbs:
  - '*'
- apiGroups:
  - base.automation.ibm.com
  resources:
  - cartridgerequirements
  - automationbases
  verbs:
  - '*'
- apiGroups:
  - eventprocessing.automation.ibm.com
  resources:
  - eventprocessors
  verbs:
  - '*'
