apiVersion: wkc.cpd.ibm.com/v1beta1
kind: WKC
metadata:
  name: wkc-cr
  namespace: REPLACE_NAMESPACE
spec:
  version: "4.0.4"
  storageClass: portworx-shared-gp3
  license:
    accept: true
    license: Enterprise
  docker_registry_prefix: cp.icr.io/cp/cpd
  useODLM: true
  # wkc_db2u_set_kernel_params: True
  # iis_db2u_set_kernel_params: True 
  # install_wkc_core_only: true     # To install the core version of the service, remove the comment tagging from the beginning of the line.