apiVersion: cde.cpd.ibm.com/v1
kind: CdeProxyService
metadata:
  name: cde-cr
  namespace: "REPLACE_NAMESPACE"
spec:
  version: 4.0.1
  storageClass: "portworx-shared-gp3"
  license:
    accept: true
    license: Enterprise  