apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: CPD_NAMESPACE
spec:
  license:
    accept: true
    license: Enterprise
  storageClass: portworx-shared-gp3
  zenCoreMetadbStorageClass: portworx-shared-gp3