apiVersion: wml.cpd.ibm.com/v1beta1
kind: WmlBase
metadata:
  name: wml-cr
  namespace: CPD_NAMESPACE
  labels:
    app.kubernetes.io/instance: wml-cr
    app.kubernetes.io/managed-by: ibm-cpd-wml-operator
    app.kubernetes.io/name: ibm-cpd-wml-operator
spec:
  ignoreForMaintenance: false
  storageClass: portworx-shared-gp3
  storageVendor: portworx
  license:
    accept: true
    license: "Enterprise"