###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operandconfigs.operator.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.phase
    description: Current Phase
    name: Phase
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Created At
    type: string
  group: operator.ibm.com
  names:
    kind: OperandConfig
    listKind: OperandConfigList
    plural: operandconfigs
    shortNames:
    - opcon
    singular: operandconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OperandConfig is the Schema for the operandconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OperandConfigSpec defines the desired state of OperandConfig
          properties:
            services:
              description: Services is a list of configuration of service
              items:
                description: ConfigService defines the configuration of the service
                properties:
                  name:
                    description: Name is the subscription name
                    type: string
                  spec:
                    additionalProperties:
                      type: object
                    description: Spec is the configuration map of custom resource
                    type: object
                  state:
                    description: State is a flag to enable or disable service
                    type: string
                required:
                - name
                - spec
                type: object
              type: array
          type: object
        status:
          description: OperandConfigStatus defines the observed state of OperandConfig
          properties:
            phase:
              description: Phase describes the overall phase of operands in the OperandConfig
              type: string
            serviceStatus:
              additionalProperties:
                description: CrStatus defines the status of the custom resource
                properties:
                  customResourceStatus:
                    additionalProperties:
                      description: ServicePhase defines the service status
                      type: string
                    type: object
                type: object
              description: ServiceStatus defines all the status of a operator
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
