###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operand-deployment-lifecycle-manager
rules:
  - apiGroups: ""
    resources: ["pods", "services", "services", "finalizers", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets", "namespaces"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: "apps"
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"] # added
  - apiGroups: "apps"
    resourceNames: "operand-deployment-lifecycle-manager"
    resources: ["deployments", "finalizers"]
    verbs: "update"
  - apiGroups: [""]
    resources: "pods"
    verbs: ["get", "list"]
  - apiGroups: "apps"
    resources: ["replicasets", "deployments"]
    verbs: "get"
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ""
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["operator.ibm.com", "operators.coreos.com"]
    resources: ["operandregistries", "operandconfigs", "operandrequests", "operandbindinfos"]
    verbs: ["get", "list", "watch", "create", "delete"]
#  - nonResourceURLs:
#    - '*'
#    verbs:
#    - '*'
