###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "ibm-db2"
  namespace: ibm-db2
spec:
  channel: v1.1
  name: db2u-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace













