kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db2oltp-cr
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - db2oltp-psp
  verbs:
    - use
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ibm-db2-role
rules:
    - apiGroups: [""]
      resources: ["pods", "pods/log", "pods/exec"]
      verbs: ["get", "list", "patch", "watch", "update", "create"]

    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list"]

    - apiGroups: ["batch", "extensions"]
      resources: ["jobs", "deployments"]
      verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-db2-rolebinding
roleRef:
    kind: Role
    name: ibm-db2-role
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: ServiceAccount
      name: db2u